"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Navbar from './navbar'
import { useState } from 'react'
import { usePathname } from 'next/navigation'
import { SessionProvider } from 'next-auth/react'

const inter = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400']
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const disableNavbar = ['/login', '/register'];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {/* tampilkan navbar jika tidak di pathname disableNavbar */}
          {!disableNavbar.includes(pathname) && <Navbar></Navbar>}
          {/* <h1>Layout {state}</h1> */}
          {/* <button onClick={() => setState(state + 1)}>Klik</button> */}
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
