"use client"
import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";
import { useState } from "react";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Web DEWaS",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isOpen, setIsOpen] = useState(true); // Initially open

  const toggleSidebar = () => {
    setIsOpen(!isOpen);
  };

  const disableNavAndSidebar = ['/', '/login', '/register'];
  const pathname = usePathname();

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/logo-bpbd.png" sizes="any" type="image/x-icon" />
        <title>DEWaS</title>
      </head>
      <body className={`${!disableNavAndSidebar.includes(pathname) && 'flex'}`}>
        {/* sidebar */}
        {/* use sidebar on page yg di perlukan */}
        {!disableNavAndSidebar.includes(pathname) &&
          <aside id="sidebar"
            className={`relative bg-gray-200 h-screen sidebar-size ${isOpen ? 'content-open' : 'content-closed hidden'
              } sm:block border-r border-gray-300 transform transition-transform`} style={{
                transition: 'margin 0.3s ease-in-out',
              }}>

            {/* sidebar content */}
            <Sidebar></Sidebar>
          </aside>
        }

        {/* navbar and main content */}
        {/* gunakan konten ini pada halaman yang di perlukan */}
        <div id="content" className="w-full flex flex-col h-screen overflow-y-hidden transform transition-transform content-open" style={{
          transition: 'margin 0.3s ease-in-out',
        }}>
          {/* navbar content */}
          {!disableNavAndSidebar.includes(pathname) && <Navbar toggleSidebar={toggleSidebar} />}
          {/* main content */}
          {children}
        </div>
      </body>
    </html>
  );
}
